services:
  - type: web
    name: be-todo
    env: docker
    dockerfilePath: ./BAckend todo/Dockerfile
    envVars:
      - key: DB_HOST
        value: YOUR_ACTUAL_HOST_HERE
      - key: DB_USER
        value: YOUR_ACTUAL_USER_HERE
      - key: DB_PASSWORD
        value: YOUR_ACTUAL_PASSWORD_HERE
      - key: DB_NAME
        value: YOUR_ACTUAL_DB_NAME_HERE
      - key: DB_PORT
        value: 5432
      - key: PORT
        value: 5000

  - type: web
    name: fe-todo
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://be-todo.onrender.com